const ADD_CALENDAR = "ADD_CALENDAR";
const LEAVE_CALENDAR = "LEAVE_CALENDAR";
const SECESSION = "SECESSION";
const CALENDAR_IMAGE_SELECT = "CALENDAR_IMAGE_SELECT";
const CREATE_CONTENT_HOME = "CREATE_CONTENT_HOME";

export default {
  ADD_CALENDAR,
  LEAVE_CALENDAR,
  SECESSION,
  CALENDAR_IMAGE_SELECT,
  CREATE_CONTENT_HOME,
};
