// QueryKeys.js

// 사용자 정보 조회
const GET_USER = "GET_USER";

// 사용자 할 일 조회
const GET_USER_TODOS = "GET_USER_TODOS";

// 사용자 즐겨찾기 일정 조회
const GET_USER_FAVORITE_TODO = "GET_USER_FAVORITE_TODO";

// 사용자 일기 조회
const GET_USER_DIARIES = "GET_USER_DIARIES";

// 달력 리스트 조회
const GET_CALENDAR_LIST = "GET_CALENDAR_LIST";

// 달력 선택 리스트 조회
const GET_CALENDAR_SELECT_LIST = "GET_CALENDAR_SELECT_LIST";

// 달력 상세 정보 조회
const GET_CALENDAR_DETAIL = "GET_CALENDAR_DETAIL";

// 달력에 작성된 글이 있는 dates 조회
const GET_CALENDAR_DATES = "GET_CALENDAR_DATES";

// 달력 기본 정보 조회
const GET_CALENDAR_BASIC = "GET_CALENDAR_BASIC";

// 초대 코드 조회
const GET_INVITE_CODE = "GET_INVITE_CODE";

// 달력 사용자 정보 조회
const GET_CALENDAR_USER_INFO = "GET_CALENDAR_USER_INFO";

// 달력 권한 조회
const GET_CALENDAR_PERMISSION = "GET_CALENDAR_PERMISSION";

// 달력 권한 리스트 조회
const GET_CALENDAR_PERMISSION_LIST = "GET_CALENDAR_PERMISSION_LIST";

// 일기 리스트 조회
const GET_DIARIES = "GET_DIARIES";

// 일기 상세 정보 조회
const GET_DIARY_DETAIL = "GET_DIARY_DETAIL";

// 캘린더 프로필 조회
const GET_CALENDAR_PROFILE = "GET_CALENDAR_PROFILE";

// 할 일 리스트 조회
const GET_TODOS = "GET_TODOS";

// 특정 달력 할 일 리스트 조회
const GET_CALENDAR_TODOS = "GET_CALENDAR_TODOS";

// 할 일 상세 정보 조회
const GET_TODO_DETAIL = "GET_TODO_DETAIL";

// 댓글 리스트 조회
const GET_COMMENTS = "GET_COMMENTS";

// 좋아요 수 조회
const GET_LIKES = "GET_LIKES";

// 캘린더 유저 조회
const GET_CALENDAR_USER = "GET_CALENDAR_USER";

// 채팅 메시지 조회
const GET_CHAT_MESSAGES = "GET_CHAT_MESSAGES";

export default {
  GET_USER,
  GET_USER_TODOS,
  GET_USER_FAVORITE_TODO,
  GET_USER_DIARIES,
  GET_CALENDAR_LIST,
  GET_CALENDAR_SELECT_LIST,
  GET_CALENDAR_DETAIL,
  GET_CALENDAR_DATES,
  GET_CALENDAR_BASIC,
  GET_INVITE_CODE,
  GET_CALENDAR_USER_INFO,
  GET_CALENDAR_PERMISSION,
  GET_CALENDAR_PERMISSION_LIST,
  GET_DIARIES,
  GET_DIARY_DETAIL,
  GET_CALENDAR_PROFILE,
  GET_TODOS,
  GET_CALENDAR_TODOS,
  GET_TODO_DETAIL,
  GET_COMMENTS,
  GET_LIKES,
  GET_CALENDAR_USER,
  GET_CHAT_MESSAGES,
};
