const DEBOUNCE_TIME = 5000;
const MAX_WIDTH = 500;
const MAX_HEIGHT = 500;
const CALENDAR_ASPECT_RATIO = 195 / 135;
const CALENDAR_TYPE = "CALENDAR_TYPE";
const ACCESS_TOKEN_EXPIRES = 86400 * 1000;
const REFRESH_TOKEN_EXPIRES = 86400 * 7 * 1000;
const TOKEN_REFRESH_THRESHOLD = 43200 * 1000;
const ADD_TYPE = "ADD_TYPE";
const EDIT_TYPE = "EDIT_TYPE";

export default {
  DEBOUNCE_TIME,
  MAX_WIDTH,
  MAX_HEIGHT,
  CALENDAR_ASPECT_RATIO,
  CALENDAR_TYPE,
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_EXPIRES,
  TOKEN_REFRESH_THRESHOLD,
  ADD_TYPE,
  EDIT_TYPE,
};
