import type { Metadata } from "next";
import "@/css/style.css";
import Providers from "@/app/Providers";
import AuthSession from "@/app/AuthSession";
import { Noto_Sans, Hi_Melody, Gaegu } from "next/font/google";

// Google Fonts에서 원하는 폰트를 불러옵니다.
const notoSans = Noto_Sans({
  subsets: ["latin"], // 원하는 서브셋 선택
  weight: ["400", "700"], // 사용할 폰트 굵기 선택
});

const hiMelody = Hi_Melody({
  subsets: ["latin"], // 원하는 서브셋 선택
  weight: ["400"], // 사용할 폰트 굵기 선택
});

const gaegu = Gaegu({
  subsets: ["latin"], // 원하는 서브셋 선택
  weight: ["400", "700", "300"], // 사용할 폰트 굵기 선택
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={gaegu.className}>
        <AuthSession>
          <Providers>{children}</Providers>
        </AuthSession>
      </body>
    </html>
  );
}
